<img src="/images/skills/React.png" alt="" className="skills-image" />
<img src="/images/skills/Next.png" alt="" className="skills-image" />
<img src="/images/skills/js.png" alt="" className="skills-image" />
<img src="/images/skills/Py.png" alt="" className="skills-image" />
<img src="/images/skills/Node.png" alt="" className="skills-image" />
<img src="/images/skills/Dj.png" alt="" className="skills-image" />
<img src="/images/skills/Mysql.png" alt="" className="skills-image" />
<img src="/images/skills/Mongo.png" alt="" className="skills-image" />
<img src="/images/skills/Fire.png" alt="" className="skills-image" />