export const projectsItem = [
  {
    id: 1,
    name: "DevLife World",
    git: "https://github.com/Pavanarathod/devlifeworld",
    link: "https://devlifeworld.web.app/",
    image: "/images/projects/Devlife.png",
  },
  {
    id: 2,
    name: "Memento Virtual Discussions",
    git: "https://github.com/Pavanarathod/memento-virtual-discussion",
    link: "https://custom-todo.web.app/",
    image: "/images/projects/Memento.png",
  },
  {
    id: 3,
    name: "Andromeda Stream",
    git: "https://github.com/Pavanarathod/edge_ledger_design",
    link: "https://andromeda-stream.web.app/",
    image: "/images/projects/Andromeda.png",
  },
  {
    id: 4,
    name: "Airbnb",
    git: "https://github.com/Pavanarathod/airbnb-with-next-js",
    link: "https://airbnb-with-next-js.vercel.app/",
    image: "/images/projects/Airbnb.png",
  },
  {
    id: 5,
    name: "Beautiful Mind",
    git: "https://github.com/Pavanarathod/beautiful-mind-nextJs-app",
    link: "https://beautiful-mind-next-js-app.vercel.app/",
    image: "/images/projects/Bm.png",
  },
  {
    id: 6,
    name: "Google Search App",
    git: "https://github.com/Pavanarathod/google-search-app-with-google-search-API",
    link: "https://googlesearchserver.vercel.app/",
    image: "/images/projects/google.png",
  },
  {
    id: 7,
    name: "Spicy Eats",
    git: "https://github.com/Pavanarathod/edge_ledger_design",
    link: "https://spicyeats-5356c.web.app/",
    image: "/images/projects/Spicy.png",
  },
  {
    id: 8,
    name: "Epic Portfolio",
    git: "https://github.com/Pavanarathod/edge_ledger_design",
    link: "https://epic-28be2.web.app/",
    image: "/images/projects/Epic.png",
  },
  {
    id: 9,
    name: "Figma Design",
    git: "https://github.com/Pavanarathod/edge_ledger_design",
    link: "https://spicyeats-5356c.web.app/",
    image: "/images/projects/Design.png",
  },
  {
    id: 10,
    name: "Mr.Robot Portfolio",
    git: "https://github.com/Pavanarathod/portfolio",
    link: "https://mr-robot.vercel.app/",
    image: "/images/projects/Mrrobot.png",
  },
];
